### ISSUE TITLE
tag docker images with branch name and tag

### ISSUE THREAD

**Issue by steinerkelvin** [agicommies/subspace-network#15]

**Comment by saiintbrisson** [comment]
@steinerkelvin should the main branch also have tagged images?

**Comment by DaviPtrs** [comment]
note to myself: currently we're tagging with just the commits short hash made on main branch

**Comment by steinerkelvin** [comment]
is this working already?

**Comment by DaviPtrs** [comment]
nop, needs to be done but it's no brain

**Comment by DaviPtrs** [comment]
Docker tags for substrate will now also follow the branch and the tag you add, so let's keep tagging properly as the substrate version increases, I had to add the 1.7.5 to the latest commit so it runs for the first time

![image](https://github.com/agicommies/subspace-network/assets/37764531/52859386-92bb-4d35-bd02-17db0905b4db)

**Comment by steinerkelvin** [comment]
We use the `v` prefix on version tags @DaviPtrs 

![image](https://github.com/agicommies/subspace-network/assets/2822370/638c1093-0456-486f-b240-315e8f0f3f47)

I'm also contemplating reflecting the substrate runtime version (e.g. `117`) in the git tags / package versions somehow to make it more trasnparent. @saiintbrisson what do ou think?

**Comment by DaviPtrs** [comment]
Tag fixed @steinerkelvin
